from Bank import Bank
def main():
    print('----------------------Shunali Bank------------------------')
    shunaliBank = Bank()
    shunaliBank.create_account("Admin")
    shunaliBank.total_balance_check('Admin')
    shunaliBank.create_account("Sajib")
    shunaliBank.create_account("Fahim")
    shunaliBank.user_deposit("Sajib", 10000)
    shunaliBank.user_deposit("Fahim", 5000)
    shunaliBank.total_balance_check('Admin')
    shunaliBank.user_withdraw("Sajib", 2000)
    shunaliBank.user_withdraw("Fahim", 1000)
    shunaliBank.total_balance_check('Admin')
    shunaliBank.user_balance_transfer("Sajib", "Fahim", 500)
    shunaliBank.user_take_loan("Sajib")
    shunaliBank.user_all_transactions("Sajib")
    shunaliBank.user_all_transactions("Fahim")
    shunaliBank.loan_shut_down('Admin') 
    shunaliBank.user_take_loan("Fahim")
    shunaliBank.loan_amount_check('Admin')
    shunaliBank.total_balance_check('Admin')

    print('----------------------HSBC Bank------------------------')

    HSBC = Bank()
    HSBC.create_account("admin")
    HSBC.total_balance_check('admin')
    HSBC.create_account("Kaled")
    HSBC.create_account("Riyad")
    HSBC.user_deposit("Kaled", 100)
    HSBC.user_deposit("Riyad", 50)
    HSBC.total_balance_check('admin')
    HSBC.user_withdraw("Kaled", 20)
    HSBC.user_withdraw("Riyad", 10)
    HSBC.total_balance_check('admin')
    HSBC.user_balance_transfer("Kaled", "Riyad", 50)
    HSBC.user_take_loan("Kaled")
    HSBC.user_all_transactions("Kaled")
    HSBC.user_all_transactions("Riyad")
    HSBC.loan_shut_down('admin') 
    HSBC.user_take_loan("Riyad")
    HSBC.loan_amount_check('admin')
    HSBC.total_balance_check('admin')


if __name__=='__main__':
    main()

